version: "3.8"
services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  identitydb:
    image: mcr.microsoft.com/mssql/server
  orderdb:
    image: mcr.microsoft.com/mssql/server
  rabbitmq:
    image: rabbitmq:3.9.4-management
  catalog.api:
    image: catalog_api_image
    build: 
      context: .
      # mevcut pathi referans alır
      dockerfile: Services/Catalog/Course.Services.Catalog/Dockerfile
  identityserver.api:
    image: identityserver_api_image
    build: 
      context: .
      # mevcut pathi referans alır
      dockerfile: IdentityServer/Course.IdentityServer/Dockerfile
      dockerfile: Services/Catalog/Course.Services.Catalog/Dockerfile
  basket.api:
    image: basket_api_image
    build: 
      context: .
      # mevcut pathi referans alır
      dockerfile: Services/Basket/Course.Services.Basket/Dockerfile
  photostock.api:
    image: photostock_api_image
    build: 
      context: .
      # mevcut pathi referans alır
      dockerfile: Services/PhotoStock/Course.Services.PhotoStock/Dockerfile
  discount.api:
    image: discount_api_image
    build: 
      context: .
      # mevcut pathi referans alır
      dockerfile: Services/Discount/Course.Services.Discount/Dockerfile
  fakepayment.api:
    image: fakepayment_api_image
    build: 
      context: .
      # mevcut pathi referans alır
      dockerfile: Services/FakePayment/Course.Services.FakePayment/Dockerfile
  order.api:
    image: order_api_image
    build: 
      context: .
      # mevcut pathi referans alır
      dockerfile: Services/Order/Course.Services.Order.API/Dockerfile
  gateway.api:
    image: gateway_api_image
    build: 
      context: .
      # mevcut pathi referans alır
      dockerfile: Gateway/Course.Gateway/Dockerfile
  aspnetcoremvc.web:
    image: aspnetcoremvc.web_image
    build: 
      context: .
      # mevcut pathi referans alır
      dockerfile: Frondends/Course.Web/Dockerfile
volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume: